"""adding departments table

Revision ID: 65ab936fb849
Revises: f9c6b8d9c4df
Create Date: 2026-06-01 14:16:34.472553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ab936fb849'
down_revision: Union[str, Sequence[str], None] = 'f9c6b8d9c4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_ROLE_ENUM = sa.Enum("UI","UX","Developer","HR",name="employeerole")
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _ROLE_ENUM.create(op.get_bind(),checkfirst=True)
    op.add_column('employees', sa.Column('role', _ROLE_ENUM, server_default='Developer', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'role')
    # ### end Alembic commands ###
