"""init

Revision ID: cd083f92ac69
Revises: 46295f2d904d
Create Date: 2026-05-29 16:05:11.000929

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd083f92ac69"
down_revision: Union[str, Sequence[str], None] = "46295f2d904d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees", sa.Column("password_hash", sa.String(length=255), nullable=True)
    )
    op.execute(
        "UPDATE employees SET password_hash = 'placeholder' WHERE password_hash is NULL"
    )
    op.alter_column("employees", "password_hash", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "password_hash")
    # ### end Alembic commands ###
